manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos/
    - name: rfpros
      url-base: https://github.com/rfpros

  defaults:
    remote: rfpros
    revision: main

  projects:
    - name: zephyr
      revision: d4600332d536caf18daeba407174fedb88f9e47a
      import: true

  self:
    path: dvk_probe
