manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos/
    - name: rfpros
      url-base: https://github.com/rfpros

  defaults:
    remote: rfpros
    revision: main

  projects:
    - name: utp_python_common_lib
      revision: 3ceca9d6c383bc7f93e47808a18a3fa6aca86825
    - name: zephyr
      revision: 19fee83f4ec36aaf7623896e3e55eb209321e777
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_rpi_pico
          - picolibc

  self:
    path: dvk_probe
